### ISSUE TITLE
Map instruments to Shift+ ... without entering the Edit mode

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#12]
Map instruments to Shift+ ... without entering the Edit mode

**Comment by GSoftwareDevelopment** [comment]
This has already been done.

In the SFX menu, you can now assign a fast key to the current SFX (instrument)

Select the SFX (while on the number, use the LEFT/RIGHT arrow keys, or RETURN and select from the list) and then press SHIFT with the number key (0 through 9) to assign the SFX.
