### ISSUE TITLE
Corrupted Player-Missile memory

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#13]
After some time of inactivity (screen saver was active) when you start to play in the tab the PMG data is corrupted.

![Altirra64_74miKyo47V](https://user-images.githubusercontent.com/88032943/127234575-b849a000-6365-4b5f-8bd5-1f52cde463b5.png)

**Comment by GSoftwareDevelopment** [comment]
This error only appeared after selecting an SFX (instrument) from the list (with CTRL+RETURN key).

This is caused by the PMG area being used as memory for the list.

Corrected by clearing the PMG memory right after exiting the SFX selection list.
