### ISSUE TITLE
Combinations Shift+ do not work during Tab play

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#14]
After pressing Ctrl+P the tab is played. You can play on the piano during this time (which is great). You can change the instruments with arrows during playing but you cannot change them with SHift+0, Shift+1 key combinations.

**Comment by GSoftwareDevelopment** [comment]
I didn't very properly describe it as a Bug, it's more of a lack of functionality. Anyway, you can already select an instrument with the fast keys (SHIFT+...) while playing TAB.

**Comment by tatqoo** [comment]
I was not sure if I selected the correct category. Obviously, it is a wish.
