### ISSUE TITLE
Incorrect frequency shift value 

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#15]
![Altirra64_cv73QXXyvp](https://user-images.githubusercontent.com/88032943/127242668-7c117182-ccc1-4d8d-878a-fc5a0acda982.png)

Look on the right. The possible range value is incorrect.

**Comment by GSoftwareDevelopment** [comment]
This error appeared not only for FREQ SHIFT, also for NOTE SHIFT and not depending on the modulation mode.

An error in defining a negative value - its representation in the MOD/VAL notation. For each value above the maximum (visible in the range) the value is negative.
However, an oversight in the condition that handled this led to a negative value being calculated for each value equal to or greater than the maximum value.

Changing the condition operation from `>=` to `>` corrected the error.
