### ISSUE TITLE
TAB definition needs one more step (128)

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#17]
In my opinion the last 127th step is not played. If you played one note every 4 steps until the end of the tab you will hear, that the last part is too short of one note. I believe, if there was another 128th step everything would played correctly.

**Comment by GSoftwareDevelopment** [comment]
Yes, there was a bug in the SFX engine.

I did a test with one note in line 127 of the TAB. It was played, however, when there was a note in the first line as well, it no longer played that last note.

I have corrected this.

**Technical note:**
However, the value that is represented in the channel registers has changed.
Previously it was TAB's Offset, now it is TAB's Row.
This does not affect the program itself, however it does change:
- playback of a single TAB by calling the `PLAY_TAB` routine, requires the row (not offset) in the parameter from which the TAB playback is to start.
