### ISSUE TITLE
Insert/delete steps in the SFX definition

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#18]
It would be very useful if it was possible to insert or remove a single step in the SFX definition. I would like to use it to define different versions of long arpeggios. It is very time consuming to redefine few dozens of note shift commands.

**Comment by GSoftwareDevelopment** [comment]
There is also similar functionality in SFX editing mode.

**Comment by tatqoo** [comment]
How to access this functionality?

**Comment by tatqoo** [comment]
I have just discovered in version 22 that same key combinations as in TAB and SONG definition work perfectly. Issue to be closed, but could you please check if anything needs to be done in Github in relation to this?

**Comment by tatqoo** [comment]
Works fine. This issue has been closed.

**Comment by tatqoo** [comment]
Works fine. This request has been closed.
