### ISSUE TITLE
Add option to change the TAB name after going there from the SONG definition

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#20]
1. Enter a number for the new TAB in the song definition
2. Shift+RETURN

It would be great if it was possible to change the new TAB name. I have to go to the TAB definition again to change the name.

**Comment by GSoftwareDevelopment** [comment]
CONTROL+N in TAB edit mode (or editing a TAB from under the SONG module) allows you to set name a TAB.

**Comment by tatqoo** [comment]
Is it new? If it is not, then it is not documented in help files.

**Comment by GSoftwareDevelopment** [comment]
There is updated documentation just not uploaded to the server yet.

**Comment by tatqoo** [comment]
Works fine. This request has been closed.
