### ISSUE TITLE
It is not possible to switch to editing of TAB #63 from the SONG module (in editing mode) by pressing SHIFT+RETURN

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [GSoftwareDevelopment/SFX-Tracker#29]

**Comment by GSoftwareDevelopment** [comment]
There is an idea to solve this application differently.
That is, use a single hotkey, such as CONTROL+S, and show a prompt telling you to enter a new step value.

**Comment by tatqoo** [comment]
I think you entered the comment in a wrong issue.
