### ISSUE TITLE
Loading default theme does not work

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#31]
I selected Dark theme and saved default.

When I restart the ATR the original color theme is loaded.

**Comment by GSoftwareDevelopment** [comment]
1. Check that the drive is set to RW mode. In Altira this is found in the FILE->Disk drives... menu
![Disk drives menu](https://ucarecdn.com/af070bac-0f89-4c8a-a530-4ed0fb4582c5/Diskaccessrules.png)
The drive must be writable (set to RW)

2. most important Save settings with SAVE DEFAULT option.
The program does not do this automatically.

If it helped, close the request) :)

**Comment by tatqoo** [comment]
Thanks!
