### ISSUE TITLE
Frequency set command in NLM SFX mode

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#36]
Quick idea - use odd distortion numbers to use as Frequency Set if Frequency Shift mode is used.
Reason: Frequency Set mode in NLM cannot be easily added

**Comment by GSoftwareDevelopment** [comment]
Done.

Effect:
In the SFX definition, odd distortion values define a temporary frequency divider setting (SET FREQ). This setting, is not accessible from the SFX function list.
The designation for this setting is the hash character '#'. The value of the frequency divider setting is determined by the MOD/VAL register in the definition. Its range is 0 to 255.
