### ISSUE TITLE
Keyboard play on the current channel during TAB edit

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#5]
Keyboard play on the current channel during TAB edit without affecting the TAB

**Comment by GSoftwareDevelopment** [comment]
In edit mode CAPS key allows to switch between: entering data into TAB / virtual piano mode.
The piano mode in TAB edition does not provide polyphony (as in SFX->PLY)
The mode is distinguished by the cursor color (in the default color theme) Red - data entry; Yellow - piano mode.

I will still want to give a message in the status bar.
