### ISSUE TITLE
Selecting instrument with SHIFT plays a note and edits TAB

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#7]
Selecting instrument with SHIFT plays a note and edits TAB. It should only select a new instrument and not edit the notes in TAB.

**Comment by GSoftwareDevelopment** [comment]
Not cleaning the variable storing the state of the last key pressed caused it to be shown as pressed in the section where the virtual piano key is checked.

The virtual piano checks the state of the key by performing an `AND $3F` operation, which removes the state of the CONTROL and SHIFT modifiers.
Masking the key state causes the SHIFT combination with keys 2,3,5,6,7,9,0 (SFX's quick select) to be treated as a piano key press.

Clearing the key's state helped get rid of the problem.
