### ISSUE TITLE
During TAB edition after selecting an instrument from the list after RETURN the list of functions is displayed

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#8]
During TAB edition after selecting an instrument from the list after RETURN the list of functions is displayed.

After selecting the instrument from the list of values program should go back to TAB editing and not to the function list.

**Comment by GSoftwareDevelopment** [comment]
By not clearing the variable that holds the state of the last pressed key, it (the RETURN key) was visible as pressed in the parent procedure.

Clearing the key's state helped get rid of the problem.
